#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.
n=1
while [ $n -le 100 ]; do
     if (( n * 3 <= 100 && n % 3 == 0 )); then
        echo "Fizz"
     fi
     if (( n * 5 <= 100 && n % 5 == 0 )); then 
        echo "Buzz"
     fi
     echo "$n"
     n=$((n+1))
done
