#!/usr/bin/env bash
# Tell the story of /etc/passwd using a while loops
while IFS=: read -r username password userid groupid info homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd

