#!/usr/bin/env bash
# Script to group Apache log visitors by IP and HTTP status code

file="${1:-access.log}"

awk '{print $1, $9}' "$file" 2>/dev/null | \
awk '{count[$1" "$2]++} END {for (key in count) print count[key], key}' | \
sort -nr


