#!/usr/bin/env bash 
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
n=1
while [ $n -le 11 ]; do
     if [ $n -eq 10 ]; then 
       echo "Hi"
     else
         echo "Best School"
     fi 
     n=$((n+1))
done 
