#!/usr/bin/env bash
# Create PID file, handle signals, and run indefinitely

echo "$$" > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"; rm -f /var/run/myscript.pid; exit' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT

while true; do
  echo "To infinity and beyond"
  sleep 2
done

