#!/usr/bin/env bash
# Indefinitely writes "I am alive!" to /tmp/my_process

while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
case "$1" in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm -f /var/run/my_process.pid
        fi
        echo "manage_my_process stopped"
        ;;
    restart)
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm -f /var/run/my_process.pid
        fi
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
